apiVersion: v1
kind: Pod
metadata:
  name: gpu-test
spec:
  restartPolicy: Never
  containers:
  - name: nvidia-smi
    image: nvidia/cuda:12.9.1-base-ubuntu22.04
    env:
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
    command: ["nvidia-smi"]
    resources:
      limits:
        nvidia.com/gpu: "1"
