apiVersion: v1
kind: Pod
metadata:
  name: mig-partitioning-example-1g
spec:
  containers:
    - name: sleepy
      image: "busybox:latest"
      command: ["sleep", "3600"]
      resources:
        limits:
          nvidia.com/mig-1g.10gb: 1