apiVersion: v1
kind: Pod
metadata:
  name: w1
spec:
  nodeSelector:
    run.ai/simulated-gpu-node-pool: pool3
  containers:
  - name: cuda-sleep
    image: nvidia/cuda:11.0.3-base-ubuntu20.04
    command: ["sleep", "3600"]
    resources:
      limits:
        nvidia.com/gpu: "1"
